// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ4fG8sea51GnvJng3hacpv4EgKeg2-YY',
    appId: '1:440669392445:web:5fb82b353b8874528c6454',
    messagingSenderId: '440669392445',
    projectId: 'seguricom-f3c2b',
    authDomain: 'seguricom-f3c2b.firebaseapp.com',
    storageBucket: 'seguricom-f3c2b.firebasestorage.app',
    measurementId: 'G-365N2HBY7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASfeb1d-zEF0qD6LlO32uGOEfeP5NXg7M',
    appId: '1:440669392445:android:81a717bc8f28c6428c6454',
    messagingSenderId: '440669392445',
    projectId: 'seguricom-f3c2b',
    storageBucket: 'seguricom-f3c2b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxvqj7sh9n3hQOZOrLNWtPwyBnn6nZtF8',
    appId: '1:440669392445:ios:5e7d0ba7969262678c6454',
    messagingSenderId: '440669392445',
    projectId: 'seguricom-f3c2b',
    storageBucket: 'seguricom-f3c2b.firebasestorage.app',
    iosBundleId: 'com.example.seguricom',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxvqj7sh9n3hQOZOrLNWtPwyBnn6nZtF8',
    appId: '1:440669392445:ios:5e7d0ba7969262678c6454',
    messagingSenderId: '440669392445',
    projectId: 'seguricom-f3c2b',
    storageBucket: 'seguricom-f3c2b.firebasestorage.app',
    iosBundleId: 'com.example.seguricom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ4fG8sea51GnvJng3hacpv4EgKeg2-YY',
    appId: '1:440669392445:web:546502cc92aba9508c6454',
    messagingSenderId: '440669392445',
    projectId: 'seguricom-f3c2b',
    authDomain: 'seguricom-f3c2b.firebaseapp.com',
    storageBucket: 'seguricom-f3c2b.firebasestorage.app',
    measurementId: 'G-ZT9G68XLGF',
  );
}
